@extends('layouts.app')


@section('content')

@include('layouts.ad')

<div class="container">
    <div class="container">
        <h1 class="text-left mt-4 ml-4 header-huisregels">Huisregels</h1>
    </div>
    <div class="container huisregels-container">
            <div>
                <h2 class="mb-3">Reclame</h2>
                <div class="text-huisregels">Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum autem cum maxime sunt illo id explicabo omnis, dolorum minima totam iure dicta eius, quae quos, cupiditate velit? Impedit sint numquam quasi iusto, amet eos dignissimos aut nostrum quas tempora delectus exercitationem repudiandae excepturi. Repudiandae provident doloribus inventore quis nesciunt minus autem fugit nemo a consectetur tempore quod, rerum ad, asperiores consequatur recusandae accusamus dolore. Exercitationem officiis delectus praesentium culpa, ducimus repellat quis deleniti beatae accusamus! Corporis accusantium cum nulla totam velit beatae, ipsam tempore ab ut blanditiis nesciunt recusandae id, eaque dignissimos neque provident ea, deserunt autem itaque nobis! Veritatis harum, tempore nulla, veniam quas laboriosam corporis distinctio nisi repellendus sunt aliquam, incidunt totam nobis iure saepe sit quos cum! Doloremque doloribus laboriosam nam eius porro voluptates itaque necessitatibus error officiis! Sit aspernatur similique dicta hic quibusdam ea fuga molestias debitis aperiam quaerat. Quod, error, doloremque dolorem praesentium cumque libero quia earum ipsa, ullam dolor sequi ea eligendi repellat. Fugit non autem sunt magnam consequatur omnis repellendus molestias labore, velit doloribus perferendis vel asperiores dolorem distinctio mollitia nulla enim rerum quasi dolores laboriosam reiciendis repellat exercitationem illo incidunt. Maxime asperiores in dolor id eveniet omnis itaque error ab optio officiis, adipisci tempora illum voluptas quos aspernatur neque quae pariatur voluptatum cumque dicta sed necessitatibus consectetur dolorem architecto. Minus totam accusamus earum veritatis maxime aliquam iure, illum dolorum, nemo excepturi veniam praesentium! Incidunt ea enim, officiis minus quidem deleniti reprehenderit dolorem, ratione aperiam qui mollitia voluptatem? Tempore eius necessitatibus esse. Sapiente, ipsum esse quisquam, rem ullam est, magni fuga aperiam necessitatibus dicta eum veritatis corporis magnam officia quia. Deleniti repellendus iusto aut a odit molestias expedita soluta laboriosam ea possimus eaque maiores nostrum quo perferendis culpa nobis at, dolorem dolorum harum quos optio dicta doloremque! Nesciunt dolores similique consequuntur ipsam sit.</div>
            </div>
    </div>
    <div class="container huisregels-container">
            <div>
                <h2 class="mb-3">Contact</h2>
                <div class="text-huisregels">Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum autem cum maxime sunt illo id explicabo omnis, dolorum minima totam iure dicta eius, quae quos, cupiditate velit? Impedit sint numquam quasi iusto, amet eos dignissimos aut nostrum quas tempora delectus exercitationem repudiandae excepturi. Repudiandae provident doloribus inventore quis nesciunt minus autem fugit nemo a consectetur tempore quod, rerum ad, asperiores consequatur recusandae accusamus dolore. Exercitationem officiis delectus praesentium culpa, ducimus repellat quis deleniti beatae accusamus! Corporis accusantium cum nulla totam velit beatae, ipsam tempore ab ut blanditiis nesciunt recusandae id, eaque dignissimos neque provident ea, deserunt autem itaque nobis! Veritatis harum, tempore nulla, veniam quas laboriosam corporis distinctio nisi repellendus sunt aliquam, incidunt totam nobis iure saepe sit quos cum! Doloremque doloribus laboriosam nam eius porro voluptates itaque necessitatibus error officiis! Sit aspernatur similique dicta hic quibusdam ea fuga molestias debitis aperiam quaerat. Quod, error, doloremque dolorem praesentium cumque libero quia earum ipsa, ullam dolor sequi ea eligendi repellat. Fugit non autem sunt magnam consequatur omnis repellendus molestias labore, velit doloribus perferendis vel asperiores dolorem distinctio mollitia nulla enim rerum quasi dolores laboriosam reiciendis repellat exercitationem illo incidunt. Maxime asperiores in dolor id eveniet omnis itaque error ab optio officiis, adipisci tempora illum voluptas quos aspernatur neque quae pariatur voluptatum cumque dicta sed necessitatibus consectetur dolorem architecto. Minus totam accusamus earum veritatis maxime aliquam iure, illum dolorum, nemo excepturi veniam praesentium! Incidunt ea enim, officiis minus quidem deleniti reprehenderit dolorem, ratione aperiam qui mollitia voluptatem? Tempore eius necessitatibus esse. Sapiente, ipsum esse quisquam, rem ullam est, magni fuga aperiam necessitatibus dicta eum veritatis corporis magnam officia quia. Deleniti repellendus iusto aut a odit molestias expedita soluta laboriosam ea possimus eaque maiores nostrum quo perferendis culpa nobis at, dolorem dolorum harum quos optio dicta doloremque! Nesciunt dolores similique consequuntur ipsam sit.</div>
            </div>
    </div>
    <div class="container huisregels-container">
            <div>
                <h2 class="mb-3">Mailen</h2>
                <div class="text-huisregels">Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum autem cum maxime sunt illo id explicabo omnis, dolorum minima totam iure dicta eius, quae quos, cupiditate velit? Impedit sint numquam quasi iusto, amet eos dignissimos aut nostrum quas tempora delectus exercitationem repudiandae excepturi. Repudiandae provident doloribus inventore quis nesciunt minus autem fugit nemo a consectetur tempore quod, rerum ad, asperiores consequatur recusandae accusamus dolore. Exercitationem officiis delectus praesentium culpa, ducimus repellat quis deleniti beatae accusamus! Corporis accusantium cum nulla totam velit beatae, ipsam tempore ab ut blanditiis nesciunt recusandae id, eaque dignissimos neque provident ea, deserunt autem itaque nobis! Veritatis harum, tempore nulla, veniam quas laboriosam corporis distinctio nisi repellendus sunt aliquam, incidunt totam nobis iure saepe sit quos cum! Doloremque doloribus laboriosam nam eius porro voluptates itaque necessitatibus error officiis! Sit aspernatur similique dicta hic quibusdam ea fuga molestias debitis aperiam quaerat. Quod, error, doloremque dolorem praesentium cumque libero quia earum ipsa, ullam dolor sequi ea eligendi repellat. Fugit non autem sunt magnam consequatur omnis repellendus molestias labore, velit doloribus perferendis vel asperiores dolorem distinctio mollitia nulla enim rerum quasi dolores laboriosam reiciendis repellat exercitationem illo incidunt. Maxime asperiores in dolor id eveniet omnis itaque error ab optio officiis, adipisci tempora illum voluptas quos aspernatur neque quae pariatur voluptatum cumque dicta sed necessitatibus consectetur dolorem architecto. Minus totam accusamus earum veritatis maxime aliquam iure, illum dolorum, nemo excepturi veniam praesentium! Incidunt ea enim, officiis minus quidem deleniti reprehenderit dolorem, ratione aperiam qui mollitia voluptatem? Tempore eius necessitatibus esse. Sapiente, ipsum esse quisquam, rem ullam est, magni fuga aperiam necessitatibus dicta eum veritatis corporis magnam officia quia. Deleniti repellendus iusto aut a odit molestias expedita soluta laboriosam ea possimus eaque maiores nostrum quo perferendis culpa nobis at, dolorem dolorum harum quos optio dicta doloremque! Nesciunt dolores similique consequuntur ipsam sit.</div>
            </div>
    </div>
</div>

@endsection
